### ISSUE TITLE
Week 10 Prototype

### ISSUE THREAD

**Issue by dean-l** [deco3500/potential-chainsaw#10]
Here we will sort out the things we each will get done for the next stand-up:
# Dean
- [ ] AJAX implementation of questions and compass
- [ ] Handling of user input (values, question answers)
# Nathan
- [ ] Coloured compass
- [ ] Comment thread
# Unassigned
- [ ] Article retrieving code
- [ ] User testing

**Comment by nathansquire67** [comment]
This has now been split into individual issues
